# Generated by Django 2.2 on 2022-11-11 18:48

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_product_name', models.CharField(help_text='导入产品名称', max_length=30, verbose_name='importProductName')),
                ('import_product_phase', models.CharField(help_text='导入产品阶段', max_length=10, verbose_name='importProductPhase')),
                ('import_date', models.DateTimeField(default=datetime.datetime.now, help_text='导入时间', verbose_name='importDate')),
            ],
            options={
                'verbose_name': 'DataImportRecords',
                'verbose_name_plural': 'DataImportRecords',
                'db_table': 'datacube_import_records',
            },
        ),
        migrations.CreateModel(
            name='SymptomCategory_First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='Category Name')),
                ('category_Desc', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='类别描述', verbose_name='Category Desc')),
                ('cratedate', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='CreateDate')),
            ],
            options={
                'verbose_name': 'Category-I',
                'verbose_name_plural': 'Category-I',
                'db_table': 'datacube_category_1',
            },
        ),
        migrations.CreateModel(
            name='SymptomCategory_Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='Category Name')),
                ('category_Desc', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='类别描述', verbose_name='Category Desc')),
                ('cratedate', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='CreateDate')),
                ('category_FirstType', models.ForeignKey(help_text='问题分类_I', on_delete=django.db.models.deletion.CASCADE, to='npi.SymptomCategory_First', verbose_name='Categoroy-I')),
            ],
            options={
                'verbose_name': 'Category-II',
                'verbose_name_plural': 'Category-II',
                'db_table': 'datacube_category_2',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processName', models.CharField(choices=[('1-SMT', 'SMT'), ('2-Off-line Assy', 'Offline-Assy'), ('3-Sub Assy Test', 'Offline-Test'), ('4-Final Assy ', 'FA'), ('5-Pre Test', 'Pre-Test'), ('6-Run-In', 'Run-In'), ('7-Image Dowanload', 'Image D/L'), ('8-OOBA ', 'OOBA'), ('9-Packing ', 'Packing')], max_length=50, verbose_name='Mfg Process')),
                ('issue_desc', models.TextField(default='', max_length=200, verbose_name='Issue Description')),
                ('impact_scope', models.CharField(choices=[('Factory', 'Factory'), ('Field ', 'Field'), ('Field + Factory', 'Field+Factory')], max_length=50, verbose_name='Impact Scope')),
                ('input_qty', models.IntegerField(verbose_name='Inputs')),
                ('defect_qty', models.IntegerField(verbose_name='Defect')),
                ('fail_rate_stage', models.TextField(default='', verbose_name='Fail By Stage')),
                ('sn', models.TextField(default='', max_length=200, verbose_name='SN Info')),
                ('sku', models.TextField(default='', max_length=200, verbose_name='SKU Info')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue/images/', verbose_name='Defect Picture')),
                ('issue_analysis', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Issue Analysis')),
                ('root_cause', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Root Cause')),
                ('root_cause_category', models.CharField(choices=[('COMM', 'COMM'), ('COMM Dfm', 'COMM Dfm'), ('COMM - Others', 'COMM-Others'), ('Commodity', 'Commodity'), ('Commodity Dfm', 'Commodity Dfm'), ('Commodity Others', 'Commodity Others'), ('Design - BIOS', 'Design-BIOS'), ('Design - EE', 'Design-EE'), ('Design - EE Dfm', 'Design-EE Dfm'), ('Design  Image Dfm', 'Design-Image Dfm'), ('Design - ME', 'Design-ME'), ('Design - ME Dfm', 'Design-ME Dfm'), ('Design - Others', 'Design-Others'), ('Design - SW', 'Design-SW'), ('Design - System Integration', 'Design-System Integration'), ('Diags', 'Diags'), ('Factory Operation', 'Factory Operation'), ('Material - BS', 'Material-BS'), ('Material - GTK', 'Material-GTK'), ('Material - Others', 'Material-Others'), ('Material - OTK', 'Material-OTK')], max_length=50, verbose_name='Root Category')),
                ('short_term', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Short Term')),
                ('short_term_category', models.CharField(choices=[('Containment - add on', 'Containment-add on'), ('Containment - rework', 'Containment-rework'), ('Containment - SOP/Fixture', 'Containment-SOP/Fixture'), ('Containment - sorting', 'Containment-sorting'), ('Inaction', 'Inaction'), ('Design', 'Design'), ('Waive', 'Waive')], max_length=50, verbose_name='Short Term Category')),
                ('long_term', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Long Term')),
                ('long_term_category', models.CharField(choices=[('Design', 'Design'), ('Supplier', 'Supplier'), ('Factory - Process', 'Factory-Process'), ('Factory - Fixture', 'Factory-Fixture')], max_length=50, verbose_name='Long Term Category')),
                ('status', models.CharField(choices=[('Gating', 'Gating'), ('Tracking', 'Tracking'), ('Close', 'Close'), ('Fix in next phase', 'Fix in next phase')], max_length=50, verbose_name='Status')),
                ('obs', models.CharField(blank=True, max_length=10, null=True, verbose_name='OBS')),
                ('duplicate', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=50, verbose_name='Duplicate?')),
                ('errorCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Error Code')),
                ('repeating', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=50, verbose_name='is Repeat Issue?')),
                ('repeatingstage', models.CharField(choices=[('SI-1', 'SI-1'), ('SI-2', 'SI-2'), ('SI-3', 'SI-3'), ('PV-1', 'PV-1'), ('PV-2', 'PV-2'), ('PV-3', 'PV-3'), ('PRB/TLD/PVR', 'PRB/TLD/PVR'), ('MV-1', 'MV-1'), ('MV-2', 'MV-2'), ('NA', 'NA')], max_length=50, verbose_name='Repeated Stage')),
                ('buildstage', models.CharField(choices=[('SI-1', 'SI-1'), ('SI-2', 'SI-2'), ('SI-3', 'SI-3'), ('PV-1', 'PV-1'), ('PV-2', 'PV-2'), ('PV-3', 'PV-3'), ('PRB/TLD/PVR', 'PRB/TLD/PVR'), ('MV-1', 'MV-1'), ('MV-2', 'MV-2'), ('NA', 'NA')], max_length=50, verbose_name='Stage')),
                ('owner', models.CharField(default='', max_length=50, verbose_name='Owner')),
                ('updatedate', models.DateField(blank=True, null=True, verbose_name='Update Date')),
                ('obs_link', models.CharField(default='', max_length=200, verbose_name='OBS Link')),
                ('cratedate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
                ('issue_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_interaction', to='npi.SymptomCategory_First', verbose_name='Category I')),
                ('issue_symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_symptom', to='npi.SymptomCategory_Second', verbose_name='Category II')),
                ('platformName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='PlatformName', to='product.Products', verbose_name='Platform Name')),
            ],
            options={
                'verbose_name': 'Safelaunch Issues',
                'verbose_name_plural': 'Safelaunch Issues',
                'db_table': 'datacube_npi_issues',
            },
        ),
    ]
