# Generated by Django 2.2 on 2022-12-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('npi', '0002_auto_20221207_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportrecords',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='root_cause_category',
            field=models.CharField(choices=[('COMM', 'COMM'), ('COMM - Dfm', 'COMM Dfm'), ('COMM - Others', 'COMM-Others'), ('Commodity', 'Commodity'), ('Commodity - Dfm', 'Commodity Dfm'), ('Commodity - Others', 'Commodity Others'), ('Design - BIOS', 'Design-BIOS'), ('Design - EE', 'Design-EE'), ('Design - EE Dfm', 'Design-EE Dfm'), ('Design  Image Dfm', 'Design-Image Dfm'), ('Design - ME', 'Design-ME'), ('Design - ME Dfm', 'Design-ME Dfm'), ('Design - Others', 'Design-Others'), ('Design - SW', 'Design-SW'), ('Design - System Integration', 'Design-System Integration'), ('Diags', 'Diags'), ('Factory Operation', 'Factory Operation'), ('Material - BS', 'Material-BS'), ('Material - GTK', 'Material-GTK'), ('Material - Others', 'Material-Others'), ('Material - OTK', 'Material-OTK')], max_length=50, verbose_name='Root Category'),
        ),
    ]
