# Generated by Django 2.2 on 2022-12-07 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0003_auto_20221207_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimportrecords',
            options={'verbose_name': 'Upload Logs', 'verbose_name_plural': 'Upload Logs'},
        ),
        migrations.AlterField(
            model_name='dataimportrecords',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='导入时间', verbose_name='Import Date'),
        ),
        migrations.AlterField(
            model_name='dataimportrecords',
            name='import_product_name',
            field=models.CharField(help_text='导入产品名称', max_length=30, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='dataimportrecords',
            name='import_product_phase',
            field=models.CharField(help_text='导入产品阶段', max_length=10, verbose_name='Product Stage'),
        ),
        migrations.AlterField(
            model_name='dataimportrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
