# Generated by Django 2.2 on 2022-12-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0004_auto_20221207_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='sku',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='SKU Info'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sn',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='SN Info'),
        ),
    ]
