# Generated by Django 2.2 on 2022-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0005_auto_20221208_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pre_build_defcet_qty',
            field=models.IntegerField(default=0, verbose_name='Prebuild Defect'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pre_build_qty',
            field=models.IntegerField(default=0, verbose_name='Prebuild Input'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_defcet_qty',
            field=models.IntegerField(default=0, verbose_name='Balance/Main Defect'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='balance_qty',
            field=models.IntegerField(default=0, verbose_name='Balance/Main Input'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fail_rate_stage',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fail By Stage'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='input_qty',
            field=models.IntegerField(verbose_name='Total Input'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mini2_build_defcet_qty',
            field=models.IntegerField(default=0, verbose_name='Mini-2 Defect'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mini2_build_qty',
            field=models.IntegerField(default=0, verbose_name='Mini-2 Input'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mini_build_defcet_qty',
            field=models.IntegerField(default=0, verbose_name='Mini-1/FAI Defect'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='mini_build_qty',
            field=models.IntegerField(default=0, verbose_name='Mini-1/FAI Input'),
        ),
    ]
