# Generated by Django 2.2 on 2022-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0006_auto_20221212_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomcategory_first',
            name='category_Name',
            field=models.CharField(default='', help_text='类别名', max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='symptomcategory_second',
            name='category_Name',
            field=models.CharField(default='', help_text='类别名', max_length=50, verbose_name='Category Name'),
        ),
    ]
