# Generated by Django 2.2 on 2022-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='yeildrate_mv',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yeild_MV'),
        ),
        migrations.AddField(
            model_name='products',
            name='yeildrate_pv',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yeild_PV'),
        ),
        migrations.AddField(
            model_name='products',
            name='yeildrate_ramp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yeild_Ramp'),
        ),
        migrations.AddField(
            model_name='products',
            name='yeildrate_si',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yeild_SI'),
        ),
    ]
