# Generated by Django 2.2 on 2022-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221111_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='yeildrate_mv',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yield_MV'),
        ),
        migrations.AlterField(
            model_name='products',
            name='yeildrate_pv',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yield_PV'),
        ),
        migrations.AlterField(
            model_name='products',
            name='yeildrate_ramp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yield_Ramp'),
        ),
        migrations.AlterField(
            model_name='products',
            name='yeildrate_si',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yield_SI'),
        ),
    ]
