# Generated by Django 2.2 on 2022-11-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221115_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='yeildrate_mv',
            new_name='yeildrate_mv_mini1',
        ),
        migrations.AddField(
            model_name='products',
            name='BuildDate_PRB_TLD_PVR',
            field=models.DateField(blank=True, null=True, verbose_name='PRB/TLD/PVR'),
        ),
        migrations.AddField(
            model_name='products',
            name='yeildrate_rtp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Yield_RTP'),
        ),
        migrations.AlterField(
            model_name='products',
            name='BuildDate_MV',
            field=models.DateField(blank=True, null=True, verbose_name='MV'),
        ),
        migrations.AlterField(
            model_name='products',
            name='BuildDate_PV',
            field=models.DateField(blank=True, null=True, verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='products',
            name='BuildDate_SI',
            field=models.DateField(blank=True, null=True, verbose_name='SI'),
        ),
        migrations.AlterField(
            model_name='products',
            name='RTP',
            field=models.DateField(blank=True, null=True, verbose_name='RTP'),
        ),
    ]
