# Generated by Django 2.2 on 2022-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductPhase',
            field=models.CharField(blank=True, choices=[('SI-1', 'SI-1'), ('SI-2', 'SI-2'), ('SI-3', 'SI-3'), ('PV-1', 'PV-1'), ('PV-2', 'PV-2'), ('PV-3', 'PV-3'), ('PRB/TLD/PVR', 'PRB/TLD/PVR'), ('MV-1', 'MV-1'), ('MV-2', 'MV-2'), ('Ramp', 'Ramp'), ('Production', 'Production')], max_length=15, null=True, verbose_name='Current Stage'),
        ),
    ]
