# Generated by Django 2.2 on 2023-03-22 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfa_Review_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfa_object', models.CharField(blank=True, max_length=50, null=True, verbose_name='Object')),
                ('dfa_estimated_hc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated HC')),
                ('dfa_production_line', models.CharField(blank=True, choices=[('FA', 'FA'), ('SA', 'SA'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='FA/SA Production Line')),
                ('dfa_cnc', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='CNC (Mock up)')),
                ('dfa_si_pv', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='SI-PV')),
                ('dfa_mv_mp', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='MV/MP')),
                ('dfa_HP_commodities_design', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name="HP's Commodities design")),
                ('dfa_odm_product_designs', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name="ODM's Product designs")),
                ('dfa_odm_packing_designs_kitting_box_design', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name="ODM's packing designs/Kitting box design")),
                ('dfa_HP_packing_designs', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name="HP's packing designs")),
                ('dfa_equipment_facilites_UPH_concerns', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='Equipment/facilites/UPH concerns')),
                ('dfa_non_match_reason_cnc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Non Match reason CNC')),
                ('dfa_non_match_reason_si', models.CharField(blank=True, max_length=50, null=True, verbose_name='Non Match reason SI')),
                ('dfa_non_match_reason_si_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Non Match reason SI-2')),
                ('dfa_non_match_reason_pv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Non Match reason PV')),
                ('dfa_odm_corrective_action_cnc', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM Corrective Action CNC')),
                ('dfa_odm_corrective_action_si', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM Corrective Action SI')),
                ('dfa_odm_corrective_action_si_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM Corrective Action SI-2')),
                ('dfa_odm_corrective_action_pv', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM Corrective Action PV')),
                ('dfa_pictures_from_factory', models.CharField(blank=True, choices=[('Y', 'Y')], max_length=50, null=True, verbose_name='Pictures from factory')),
                ('dfa_HP_internal_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='HP internal discussion(PE/ME)')),
                ('dfa_HP_internal_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=50, null=True, verbose_name='HP internal assessment (PE/ME)')),
                ('dfa_crate_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Dfa result',
                'verbose_name_plural': 'Dfa result',
                'db_table': 'datacube_dfa_result',
            },
        ),
        migrations.CreateModel(
            name='Dfa_Report_Import_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_product_name', models.CharField(help_text='导入产品名称', max_length=30, verbose_name='Product Name')),
                ('import_object', models.CharField(help_text='Project name', max_length=50, null=True, verbose_name='Project name')),
                ('import_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date', verbose_name='Update Date')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dfa_DataImportRecords',
                'verbose_name_plural': 'Dfa_DataImportRecords',
                'db_table': 'datacube_dfa_import_records',
            },
        ),
    ]
