# Generated by Django 2.2 on 2023-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dfa_report_import_records',
            options={'verbose_name': 'Upload logs', 'verbose_name_plural': 'Upload logs'},
        ),
    ]
