# Generated by Django 2.2 on 2023-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0002_auto_20230322_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfa_report_import_records',
            name='import_object',
        ),
        migrations.AddField(
            model_name='dfa_report_import_records',
            name='import_odm',
            field=models.CharField(default=3, max_length=30, verbose_name='ODM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dfa_report_import_records',
            name='import_product_name',
            field=models.CharField(max_length=30, verbose_name='Product Name'),
        ),
    ]
