# Generated by Django 2.2 on 2023-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0004_dfa_review_result_dfa_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_object',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Object'),
        ),
    ]
