# Generated by Django 2.2 on 2023-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0006_dfa_review_result_dfa_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_category',
            field=models.CharField(choices=[('Bonding', 'Bonding'), ('Gluing', 'Gluing'), ('Assembly', 'Assembly'), ('Screwing', 'Screwing'), ('Cables Assembly', 'Cables Assembly'), ('Material Scan & link', 'Material Scan & link'), ('Audits', 'Audits'), ('Test', 'Test'), ('Labeling & Packing', 'Labeling & Packing')], max_length=50, null=True, verbose_name='Category'),
        ),
    ]
