# Generated by Django 2.2 on 2023-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0007_auto_20230323_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_object',
            field=models.CharField(max_length=100, null=True, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_production_line',
            field=models.CharField(blank=True, choices=[('FA', 'FA'), ('SA', 'SA'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='Production Line'),
        ),
    ]
