# Generated by Django 2.2 on 2023-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0008_auto_20230323_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_HP_internal_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=50, null=True, verbose_name='HP internal assessment(PE/ME)'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_cnc',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='CNC'),
        ),
    ]
