# Generated by Django 2.2 on 2023-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0009_auto_20230323_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_HP_commodities_design',
            field=models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='CMDT_design_HP'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_HP_internal_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=50, null=True, verbose_name='INTL_ASS_HP'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_HP_internal_discussion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='INTL_CMT_HP'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_HP_packing_designs',
            field=models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='PACK_design_HP'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_equipment_facilites_UPH_concerns',
            field=models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='EQT/FAC/UPH concern'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_estimated_hc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. HC'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_mv_mp',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='MV-MP'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_non_match_reason_cnc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_CNC'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_non_match_reason_pv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_PV'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_non_match_reason_si',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_SI'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_non_match_reason_si_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_SI2'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_object',
            field=models.CharField(max_length=100, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_corrective_action_cnc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_CNC'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_corrective_action_pv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_PV'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_corrective_action_si',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_SI'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_corrective_action_si_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_SI2'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_packing_designs_kitting_box_design',
            field=models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='PACK_BOX_design_ODM'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_odm_product_designs',
            field=models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=50, null=True, verbose_name='Product_design_ODM'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_pictures_from_factory',
            field=models.CharField(blank=True, choices=[('Y', 'Y')], max_length=50, null=True, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_production_line',
            field=models.CharField(blank=True, choices=[('FA', 'FA'), ('SA', 'SA'), ('N/D', 'N/D')], max_length=50, null=True, verbose_name='PL'),
        ),
    ]
