# Generated by Django 2.2 on 2023-03-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0012_auto_20230323_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_estimated_hc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Est. HC'),
        ),
    ]
