# Generated by Django 2.2 on 2023-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0013_auto_20230323_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_estimated_hc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. HC'),
        ),
    ]
