# Generated by Django 2.2 on 2023-03-23 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0014_auto_20230323_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfa_review_result',
            name='dfa_crate_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='CreateDate'),
        ),
    ]
