# Generated by Django 2.2 on 2023-03-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfa', '0015_auto_20230323_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfa_review_result',
            old_name='dfa_non_match_reason_si_2',
            new_name='dfa_non_match_reason_si2',
        ),
        migrations.RenameField(
            model_name='dfa_review_result',
            old_name='dfa_odm_corrective_action_si_2',
            new_name='dfa_odm_corrective_action_si2',
        ),
    ]
