# Generated by Django 2.2 on 2023-04-11 09:59

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpe_owner', models.CharField(choices=[('Kevin Qian', 'Kevin Qian'), ('Wilson Xiao', 'Wilson Xiao'), ('Scott She', 'Scott She'), ('Chris Cui', 'Chris Cui'), ('Ivy Zeng', 'Ivy Zeng'), ('Niko Zhou', 'Niko Zhou'), ('Damon Wang', 'Damon Wang'), ('Tian Zhang', 'Tian Zhang'), ('Miller Shih', 'Miller Shih'), ('Franky He', 'Franky He'), ('Matt Peng', 'Matt Peng')], max_length=50, verbose_name='Platform PE')),
                ('odm_name', models.CharField(choices=[('IMX', 'IMX'), ('India', 'India')], max_length=15, verbose_name='Factory')),
                ('process_name', models.CharField(choices=[('1-SMT', 'SMT'), ('2-Off-line Assy', 'Offline-Assy'), ('3-Sub Assy Test', 'Offline-Test'), ('4-Final Assy ', 'FA'), ('5-Pre Test', 'Pre-Test'), ('6-Run-In', 'Run-In'), ('7-Image Download', 'Image D/L'), ('8-OOBA ', 'OOBA'), ('9-Packing ', 'Packing')], max_length=50, verbose_name='Mfg Process')),
                ('product_segment', models.CharField(choices=[('1000', '1000'), ('800', '800'), ('600', '600'), ('400', '400'), ('mWS', 'mWS'), ('Spectre', 'Spectre'), ('ENVY', 'ENVY'), ('Pavilion', 'Pavilion'), ('OMEN', 'OMEN'), ('Pavilion Gaming', 'Pavilion Gaming'), ('OPP', 'OPP'), ('Victus', 'Victus'), ('Chromebook', 'Chromebook'), ('Education', 'Education'), ('Dock', 'Dock'), ('TC', 'TC'), ('RPOS', 'RPOS')], max_length=20, verbose_name='Segment')),
                ('build_stage', models.CharField(choices=[('P/R-1', 'P/R-1'), ('P/R-2', 'P/R-2'), ('Sustaining', 'Sustaining'), ('Field', 'Field')], max_length=50, verbose_name='Stage')),
                ('impact_scope', models.CharField(choices=[('Factory', 'Factory'), ('Field ', 'Field'), ('Field + Factory', 'Field+Factory')], max_length=50, verbose_name='Impact Scope')),
                ('input_qty', models.IntegerField(verbose_name='Input')),
                ('defect_qty', models.IntegerField(verbose_name='Defect')),
                ('fail_rate_stage', models.IntegerField(blank=True, null=True, verbose_name='Failure Rate')),
                ('issue_status', models.CharField(choices=[('Gating', 'Gating'), ('Tracking', 'Tracking'), ('Close', 'Close'), ('Fix in next phase', 'Fix in next phase')], max_length=50, verbose_name='Issue Status')),
                ('issue_photo', models.ImageField(blank=True, null=True, upload_to='region_case/images/', verbose_name='Defect Picture')),
                ('issue_desc', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Issue Description and Investigation')),
                ('root_cause', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Root Cause')),
                ('root_cause_category', models.CharField(choices=[('COMM', 'COMM'), ('COMM - Dfm', 'COMM Dfm'), ('COMM - Others', 'COMM-Others'), ('Commodity', 'Commodity'), ('Commodity - Dfm', 'Commodity Dfm'), ('Commodity - Others', 'Commodity Others'), ('Design - BIOS', 'Design-BIOS'), ('Design - EE', 'Design-EE'), ('Design - EE Dfm', 'Design-EE Dfm'), ('Design - Image Dfm', 'Design-Image Dfm'), ('Design - ME', 'Design-ME'), ('Design - ME Dfm', 'Design-ME Dfm'), ('Design - Others', 'Design-Others'), ('Design - SW', 'Design-SW'), ('Design - System Integration', 'Design-System Integration'), ('Diags', 'Diags'), ('Factory Operation', 'Factory Operation'), ('Material - BS', 'Material-BS'), ('Material - GTK', 'Material-GTK'), ('Material - Others', 'Material-Others'), ('Material - OTK', 'Material-OTK')], max_length=50, verbose_name='Root-cause Category')),
                ('short_term', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Short-Term')),
                ('short_term_category', models.CharField(choices=[('Containment - add on', 'Containment-add on'), ('Containment - rework', 'Containment-rework'), ('Containment - SOP/Fixture', 'Containment-SOP/Fixture'), ('Containment - sorting', 'Containment-sorting'), ('Inaction', 'Inaction'), ('Design', 'Design'), ('Waive', 'Waive')], max_length=50, verbose_name='Short-term Category')),
                ('long_term', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Long-Term')),
                ('long_term_category', models.CharField(choices=[('Design', 'Design'), ('Supplier', 'Supplier'), ('Factory - Process', 'Factory-Process'), ('Factory - Fixture', 'Factory-Fixture')], max_length=50, verbose_name='Long-term Category')),
                ('crate_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
                ('platform_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='product.Products', verbose_name='Platform Name')),
                ('rpe_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpe', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'case',
                'db_table': 'datacube_regional_issue',
            },
        ),
    ]
