# Generated by Django 2.2 on 2023-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioncase', '0002_auto_20230524_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncase',
            name='odm_name',
            field=models.CharField(choices=[('IMX', 'IMX'), ('India', 'India')], max_length=15, verbose_name='Factory'),
        ),
    ]
