# Generated by Django 2.2 on 2023-05-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioncase', '0003_auto_20230411_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncase',
            name='odm_name',
            field=models.CharField(choices=[('India', 'India'), ('IMX', 'IMX')], max_length=15, verbose_name='Factory'),
        ),
    ]
