# Generated by Django 2.2 on 2023-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalcase',
            name='odm_name',
            field=models.CharField(choices=[('India', 'India'), ('IMX', 'IMX')], max_length=15, verbose_name='Factory'),
        ),
    ]
