# Generated by Django 2.2 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0002_auto_20230509_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalcase',
            name='odm_name',
            field=models.CharField(choices=[('IMX', 'IMX'), ('India', 'India')], max_length=15, verbose_name='Factory'),
        ),
    ]
